### ISSUE TITLE
using network image  instead of uiimage

### ISSUE THREAD

**Issue by fukemy** [SteveBarnegren/AttributedStringBuilder#4]
Hi, thanks for your lib. I want to ask the updating feature like my above title. Can you help?

**Comment by SteveBarnegren** [comment]
Hi @fukemy 

Networking is really out of the scope of `AttributedStringBuilder`. If you wanted to use a networked image, then the approach to take would be to download the image first, and then use it to create your attributed string. You can download an image using `URLSession`, or with a library like [Kingfisher](https://github.com/onevcat/Kingfisher).
